flowchart LR
    subgraph theme
        jinja[jinja2-cli]
        pandoc
        css[custom css]
        pagedjs-cli
        markdown[Template]
    end
    input ---> |json|jinja
    markdown --> |jinja markdown|jinja
    jinja --markdown--> pandoc
    pandoc --html--> pagedjs-cli
    css --css--> pagedjs-cli
    pagedjs-cli --pdf--> output

